name: instagram_flutter
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_auth: ^4.1.2
  firebase_storage: ^11.0.5
  cloudflare: ^3.2.1+1
  flutter_svg: ^1.1.6
  image_picker: ^0.8.4
  file_picker: ^5.2.2
  provider: ^6.0.4
  uuid: ^3.0.7
  intl: ^0.18.0
  flutter_staggered_grid_view: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/ic_instagram.svg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

