// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kvewG5Vau7rM5VQa-tDKwgZvMxfTptI',
    appId: '1:331814003838:web:63561b2fafdc5f8a2ea42f',
    messagingSenderId: '331814003838',
    projectId: 'instagram-clone-c2645',
    authDomain: 'instagram-clone-c2645.firebaseapp.com',
    databaseURL: 'https://instagram-clone-c2645-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-c2645.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanxsYMueW78Vaz5NDNW0N5Yu3Nw0w4_8',
    appId: '1:331814003838:android:5640ed725dd2ab792ea42f',
    messagingSenderId: '331814003838',
    projectId: 'instagram-clone-c2645',
    databaseURL: 'https://instagram-clone-c2645-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-c2645.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVy09rRKxv0Y_64kyI80oYr_2oEDghCQ',
    appId: '1:331814003838:ios:1a95df7defea06152ea42f',
    messagingSenderId: '331814003838',
    projectId: 'instagram-clone-c2645',
    databaseURL: 'https://instagram-clone-c2645-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-c2645.appspot.com',
    iosClientId: '331814003838-79fglnnkn067a11a5g1aid0lsn9ibksk.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEVy09rRKxv0Y_64kyI80oYr_2oEDghCQ',
    appId: '1:331814003838:ios:1a95df7defea06152ea42f',
    messagingSenderId: '331814003838',
    projectId: 'instagram-clone-c2645',
    databaseURL: 'https://instagram-clone-c2645-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'instagram-clone-c2645.appspot.com',
    iosClientId: '331814003838-79fglnnkn067a11a5g1aid0lsn9ibksk.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
